<#
.SYNOPSIS
    Run the Clean Media worker as a Windows background service.

.DESCRIPTION
    Registers a scheduled task that starts the worker at boot, before anyone
    logs in, and restarts it if it crashes. Jellyfin silently reports no
    segments whenever the worker is down, so it needs to be up whenever
    Jellyfin is.

    This uses Task Scheduler rather than a real service (sc.exe / New-Service)
    because uvicorn is a console program, not a service binary — a real
    service would need NSSM or WinSW wrapped around it for no practical gain.
    Task Scheduler already does start-at-boot, restart-on-failure, and
    run-without-login.

    Run from an *elevated* PowerShell: registering a boot-time task that runs
    without a logged-in user requires administrator rights.

.PARAMETER Port
    Port the worker listens on. Must match the Worker URL in the Jellyfin
    plugin settings.

.PARAMETER MediaRoots
    Semicolon-separated folders to search when Jellyfin asks about a file by
    its own path (/volume1/Movies/...) that does not exist on this machine.
    Defaults to <repo>\movies.

.PARAMETER UsePassword
    Store your Windows password with the task. Only needed if MediaRoots
    points at a UNC path or mapped drive — without it the task runs with no
    network credentials and cannot reach an SMB share. Local paths do not
    need this.

.PARAMETER Uninstall
    Remove the task.

.EXAMPLE
    # From an elevated PowerShell, in the repo root:
    .\scripts\install-service.ps1

.EXAMPLE
    .\scripts\install-service.ps1 -MediaRoots "D:\Movies;D:\TV" -Port 8765

.EXAMPLE
    .\scripts\install-service.ps1 -Uninstall
#>
[CmdletBinding()]
param(
    [int]$Port = 8765,
    [string]$MediaRoots,
    [string]$TaskName = 'CleanMediaWorker',
    [switch]$UsePassword,
    [switch]$Uninstall
)

$ErrorActionPreference = 'Stop'

$repo = Split-Path -Parent $PSScriptRoot

function Assert-Elevated {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($id)
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw "Run this from an elevated PowerShell (right-click -> Run as administrator)."
    }
}

Assert-Elevated

if ($Uninstall) {
    $existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($null -eq $existing) {
        Write-Host "No task named '$TaskName'. Nothing to do."
        return
    }
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Host "Removed scheduled task '$TaskName'. The worker will not start at boot."
    Write-Host "Logs and the launcher are left in place under $env:LOCALAPPDATA\CleanMedia."
    return
}

# --- locate uv -------------------------------------------------------------
# uv installs to ~\.local\bin, which is not on the PATH a scheduled task gets,
# so resolve it to an absolute path now and bake that into the launcher.
$uv = $null
$found = Get-Command uv -ErrorAction SilentlyContinue
if ($null -ne $found) {
    $uv = $found.Source
} else {
    $candidates = @(
        (Join-Path $env:USERPROFILE '.local\bin\uv.exe'),
        (Join-Path $env:LOCALAPPDATA 'Programs\uv\uv.exe'),
        (Join-Path $env:LOCALAPPDATA 'Microsoft\WinGet\Links\uv.exe')
    )
    foreach ($c in $candidates) {
        if (Test-Path $c) { $uv = $c; break }
    }
}
if ($null -eq $uv) {
    throw "uv not found. Install it with: winget install astral-sh.uv"
}

if ([string]::IsNullOrWhiteSpace($MediaRoots)) {
    $MediaRoots = Join-Path $repo 'movies'
}

# A worker already started by hand holds the port, and the task would die on
# startup with a bind error that only shows up in the log.
$inUse = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue
if ($null -ne $inUse) {
    $owner = Get-Process -Id $inUse[0].OwningProcess -ErrorAction SilentlyContinue
    $name = if ($null -eq $owner) { 'unknown' } else { "$($owner.ProcessName) (pid $($owner.Id))" }
    throw "Port $Port is already in use by $name. Stop it first -- probably a worker you started by hand."
}

# --- write the launcher ----------------------------------------------------
# A scheduled task action cannot set environment variables, so the task runs a
# small .cmd that sets them and then execs uv. It lives outside the repo so it
# is not something you have to remember to gitignore.
$stateDir = Join-Path $env:LOCALAPPDATA 'CleanMedia'
if (-not (Test-Path $stateDir)) { New-Item -ItemType Directory -Path $stateDir | Out-Null }
$launcher = Join-Path $stateDir 'worker-service.cmd'
$logPath = Join-Path $stateDir 'worker.log'

# Generated, not checked in: every value below is machine-specific.
$cmd = @"
@echo off
rem Generated by scripts\install-service.ps1 -- edits here are overwritten on reinstall.
set "CLEANMEDIA_MEDIA_ROOTS=$MediaRoots"
cd /d "$repo"

rem Keep the log from growing without bound across reboots.
for %%A in ("$logPath") do if %%~zA GTR 10485760 del "$logPath"

echo. >> "$logPath"
echo ==== starting worker on port $Port ==== >> "$logPath"
"$uv" run uvicorn worker.main:app --host 0.0.0.0 --port $Port >> "$logPath" 2>&1
"@
Set-Content -Path $launcher -Value $cmd -Encoding ASCII

# --- register the task -----------------------------------------------------
$action = New-ScheduledTaskAction -Execute $launcher -WorkingDirectory $repo
$trigger = New-ScheduledTaskTrigger -AtStartup

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -RestartCount 999 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero)   # never time out: this runs forever

$user = "$env:USERDOMAIN\$env:USERNAME"

$register = @{
    TaskName    = $TaskName
    Action      = $action
    Trigger     = $trigger
    Settings    = $settings
    Description = "Clean Media analysis worker. Serves approved segments to the Jellyfin plugin."
    Force       = $true
}

if ($UsePassword) {
    # Stored credentials, so the task has network access to UNC media roots.
    $cred = Get-Credential -UserName $user -Message "Windows password for $user (stored with the task)"
    $register.User = $cred.UserName
    $register.Password = $cred.GetNetworkCredential().Password
    $register.RunLevel = 'Limited'
} else {
    # S4U: runs whether or not you are logged in, without storing a password.
    # The tradeoff is no network credentials -- fine for local media roots.
    $register.Principal = New-ScheduledTaskPrincipal -UserId $user -LogonType S4U -RunLevel Limited
}

Register-ScheduledTask @register | Out-Null
Write-Host "Registered scheduled task '$TaskName'."
Write-Host "  launcher   $launcher"
Write-Host "  log        $logPath"
Write-Host "  media root $MediaRoots"

# --- start and verify ------------------------------------------------------
# Verify the invariant, not the exit code: a task that starts and immediately
# dies still reports success.
Start-ScheduledTask -TaskName $TaskName
Write-Host ""
Write-Host "Waiting for the worker to answer on port $Port. First start loads the"
Write-Host "speech and vision models, which takes a minute or two..."

# Generous: a cold start on this machine took ~70s, and a too-short wait
# would report failure on a worker that was merely still loading.
$healthy = $false
foreach ($i in 1..90) {
    try {
        $r = Invoke-RestMethod -Uri "http://127.0.0.1:$Port/api/health" -TimeoutSec 2
        Write-Host "Worker $($r.version) is up after $($i * 2)s."
        Write-Host "  engines: $(($r.engines.PSObject.Properties.Name) -join ', ')"
        $healthy = $true
        break
    } catch {
        Start-Sleep -Seconds 2
    }
}

if (-not $healthy) {
    Write-Warning "The worker did not answer within 3 minutes. Check the log:"
    Write-Warning "  Get-Content '$logPath' -Tail 40"
    exit 1
}

$ips = Get-NetIPAddress -AddressFamily IPv4 |
    Where-Object { $_.IPAddress -notlike '127.*' -and $_.IPAddress -notlike '169.254.*' } |
    Select-Object -ExpandProperty IPAddress

Write-Host ""
Write-Host "Set the Worker URL in the Jellyfin plugin settings to one of:"
foreach ($ip in $ips) { Write-Host "    http://${ip}:$Port" }
Write-Host ""
Write-Host "Use the address on the same LAN as your Jellyfin server. A Tailscale"
Write-Host "address will not work if Jellyfin runs in a Docker bridge network."
