#!/bin/bash
# Generated by scripts/install.sh from this template (scripts/pkg/worker-icon.command)
# -- re-run install.sh, or scripts/install-service.sh directly, to change
# settings without going through this menu. __REPO__ and __UV__ are filled in
# at install time; everything else is resolved live, every time this opens.
set -u
PORT=8765
REPO="__REPO__"
UV="__UV__"
LABEL="com.cleanmedia.worker"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
HEALTH="http://127.0.0.1:$PORT/api/health"

# The plist (if the background service is installed) is the one source of
# truth for the current media folder(s) / VLM hosts -- reading it fresh each
# time means this never drifts from what's actually configured, and there's
# nothing here to keep in sync by hand.
current_media_roots() {
  [ -f "$PLIST" ] && sed -n 's#.*<key>CLEANMEDIA_MEDIA_ROOTS</key><string>\(.*\)</string>.*#\1#p' "$PLIST"
}
current_vlm_hosts() {
  [ -f "$PLIST" ] && sed -n 's#.*<key>CLEANMEDIA_VLM_HOSTS</key><string>\(.*\)</string>.*#\1#p' "$PLIST"
}

show_status() {
  echo "Clean Media Worker"
  echo "-------------------"
  body="$(curl -fsS --max-time 5 "$HEALTH" 2>/dev/null || true)"
  if [ -n "$body" ]; then
    # grep -o + head -1, not a greedy sed pattern: each engine can report its
    # own "version" too (e.g. whisper's faster-whisper version) -- a greedy
    # .*"version":".* grabs the LAST match in the string, not the worker's
    # own version, which is first.
    ver="$(printf '%s' "$body" | grep -o '"version":"[^"]*"' | head -1 | sed 's/^"version":"//; s/"$//')"
    queue="$(printf '%s' "$body" | grep -o '"queueSize":[0-9]*' | head -1 | sed 's/^"queueSize"://')"
    paused=""
    printf '%s' "$body" | grep -q '"paused":true' && paused=" -- paused"
    gpuname="$(printf '%s' "$body" | sed -n 's/.*"gpu":{"available":true,"name":"\([^"]*\)".*/\1/p')"
    echo "  status   : online (v${ver:-?})"
    echo "  gpu      : ${gpuname:-none}"
    echo "  queue    : ${queue:-0} job(s)${paused}"
  else
    echo "  status   : offline"
  fi

  service_state="not set up (running directly, if at all -- see option 1)"
  [ -f "$PLIST" ] && service_state="runs automatically at login"
  echo "  service  : $service_state"

  mr="$(current_media_roots)"
  if [ -n "$mr" ]; then
    IFS=: read -ra roots <<< "$mr"
    for r in "${roots[@]}"; do
      [ -n "$r" ] || continue
      if [ -d "$r" ]; then echo "  media    : ok       $r"
      else echo "  media    : warn     not found right now (unmounted?): $r"; fi
    done
  fi
  vh="$(current_vlm_hosts)"
  if [ -n "$vh" ]; then
    IFS=, read -ra hosts <<< "$vh"
    for h in "${hosts[@]}"; do
      [ -n "$h" ] || continue
      if curl -fsS --max-time 3 "$h/api/tags" >/dev/null 2>&1; then echo "  vlm host : ok       $h"
      else echo "  vlm host : warn     unreachable right now: $h"; fi
    done
  fi
  echo
}

run_directly() {
  # No service, or it's not cooperating -- run it right here so this icon
  # always gets you a working worker. Closing this window stops it.
  echo "Starting the worker directly in this window (closing this window stops it)..."
  cd "$REPO"
  exec "$UV" run uvicorn worker.main:app --host 0.0.0.0 --port "$PORT"
}

pause() { read -r -p "Press Enter to continue... " _ || true; }

while true; do
  clear 2>/dev/null || true
  show_status
  echo "  1) Restart the worker"
  echo "  2) Change the media folder / VLM hosts"
  echo "  3) View recent activity"
  echo "  4) Quit this window"
  echo
  read -r -p "> " choice || exit 0
  case "$choice" in
    1)
      if [ -f "$PLIST" ]; then
        bash "$REPO/scripts/install-service.sh" --restart
      else
        echo "No background service is set up yet."
        read -r -p "Set one up now, so it starts automatically from here on? [Y/n] " yn || yn=n
        case "$yn" in
          [Nn]*) run_directly ;;
          *) bash "$REPO/scripts/install-service.sh" ;;
        esac
      fi
      pause ;;
    2)
      cur_mr="$(current_media_roots)"; [ -z "$cur_mr" ] && cur_mr="$REPO/movies"
      cur_vh="$(current_vlm_hosts)"
      read -r -p "Media folder(s), colon-separated [$cur_mr]: " new_mr || new_mr=""
      new_mr="${new_mr:-$cur_mr}"
      read -r -p "VLM hosts, comma-separated, blank for local only [$cur_vh]: " new_vh || new_vh=""
      new_vh="${new_vh:-$cur_vh}"
      args=(--media-roots "$new_mr")
      [ -n "$new_vh" ] && args+=(--vlm-hosts "$new_vh")
      [ -f "$PLIST" ] && args+=(--restart)
      bash "$REPO/scripts/install-service.sh" "${args[@]}"
      pause ;;
    3)
      LOGFILE_WORKER="$REPO/data/logs/worker.log"
      if [ -f "$LOGFILE_WORKER" ]; then tail -n 20 "$LOGFILE_WORKER"; else echo "(no activity logged yet)"; fi
      pause ;;
    4) exit 0 ;;
    *) ;;
  esac
done
